# Generated by Django 3.2 on 2021-06-21 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='month_id',
            new_name='month',
        ),
    ]
