# Generated by Django 3.2 on 2021-06-22 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0002_rename_month_id_transaction_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='month',
            name='start_month_balance',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='month',
            name='start_month_savings',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
