# Generated by Django 3.2 on 2021-05-29 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0002_alter_group_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Month',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(choices=[('2021', '2021'), ('2022', '2022'), ('2023', '2023')], max_length=4)),
                ('month', models.CharField(choices=[('January', 'January'), ('February', 'February'), ('March', 'March'), ('April', 'April'), ('May', 'May'), ('June', 'June'), ('July', 'July'), ('August', 'August'), ('September', 'September'), ('October', 'October'), ('November', 'November'), ('December', 'December')], max_length=15)),
                ('start_month_savings', models.DecimalField(decimal_places=2, max_digits=8)),
                ('start_month_balance', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
    ]
