# Generated by Django 3.2 on 2021-05-29 14:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('budget', '0003_month'),
    ]

    operations = [
        migrations.AddField(
            model_name='month',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='months', to='auth.user'),
            preserve_default=False,
        ),
    ]
