# Generated by Django 3.2 on 2021-06-06 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0003_alter_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='group',
            field=models.CharField(choices=[('Expense', 'Expense'), ('Income', 'Income'), ('Savings', 'Savings')], max_length=7),
        ),
    ]
