# Generated by Django 3.2 on 2021-06-06 17:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('budget', '0004_alter_category_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='month',
            name='start_month_balance',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='month',
            name='start_month_savings',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='month',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
