# Generated by Django 3.2 on 2021-05-24 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('transaction', '0001_initial'),
        ('authtoken', '0003_tokenproxy'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
